### ISSUE TITLE
Custom Listener

### ISSUE THREAD

**Issue by jfortier** [stof/StofDoctrineExtensionsBundle#12]
Hey Stof,

I'm trying to override the default Listener for my own. Changing it directly in the XML works, but overriding in config.yml does not work. Here is my code. which is directly from your documentation with obvious changes to the class name. 

<code>
stof_doctrine_extensions:
    class:
        orm:
            translatable: MRX\Common\MrxCoreBundle\ORM\TranslationListener
</code>

I guess I can just fork your code, but this should be easy to override. 

Thanks,

Justin Fortier

**Comment by VBelozyorov** [comment]
How should I do if my custom listener needs some additional constructor argument?

I want to log user_id instead of username, so I tried to inject `@security.token_storage` into my listener and extract user from there. But that leads to error during container compile:
```
Too few arguments to function App\EventSubscriber\LoggableListener::__construct(), 0 passed in /var/www/app/var/cache/dev/ContainerQeDNUly/srcApp_KernelDevDebugContainer.php on line 2259 and exactly 1 expected
```
I've tried to override whole `stof_doctrine_extensions.listener.loggable` service and seems container was built, but now methods of base listener are not called anymore (`prePersistLogEntry`, `onFlush` and so on).

**Comment by mleczakm** [comment]
@VBelozyorov did you manage to fix this error?

**Comment by coderpauloo** [comment]
Hi, anyone found a way to pass extra arguments to a custom listener please ?

I'm currently struggling with this since I try to override the prePersistLogEntry method in order to set properties on my CustomLogEntry entity, I would like to log the user firstname, lastname and ID aswell  :'(

Thanks for your help

**Comment by DaveData** [comment]
> Hi, anyone found a way to pass extra arguments to a custom listener please ?

Stumbled upon this ticket while converting the configs from yaml->php.

You can decorate the service:

```php
// config/services.php
    $services->set(LoggableListener::class)
        ->decorate('stof_doctrine_extensions.listener.loggable')
        ->arg('$logTaggers', tagged_iterator('app.log_tagger'))
    ;

```

or yaml
```yaml
services:
      App\Loggable\LoggableListener:
            decorates: 'stof_doctrine_extensions.listener.loggable'
            arguments:
                  $logTaggers: !tagged app.log_tagger
```
