### ISSUE TITLE
[Blameable] Not working from Console commands

### ISSUE THREAD

**Issue by tiagojsag** [stof/StofDoctrineExtensionsBundle#197]
Hi,

I'm trying to create a bunch of instances from a console command, and I noticed that the BlameListener's onKernelRequest is not being called. I'm guessing Console commands don't trigger kernel events like traditional requests. Is there any way this can be addressed?

cheers

**Comment by BPScott** [comment]
Holy necroposting Batman! I ran into this today and found the solution...

Setting a user within the `security.context` does not work as the `BlameListener` only sets up the username from the `security.context` when the `KernelEvents::REQUEST` is triggered. This is only part of the HTTP lifecycle, not the console lifecycle, and thus it never gets called. However instead of relying on that event can set the user value of the `BlameableListener` explicitly.

In your fixture file [make sure that it implements the ContainerAwareInterface](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#using-the-container-in-the-fixtures), then prior to creating your fixture entities add the following line (where the contents of setUserValue is whatever you want stored in your Blameable field):

```php
$this->container->get('stof_doctrine_extensions.listener.blameable')
            ->setUserValue('fixture.generator@example.com');
```

**Comment by cmfcmf** [comment]
I'm afraid the method proposed by @BPScott will break in Symfony 4. The `stof_doctrine_extensions.listener.blameable` service is marked as private and can therefore not be retrieved from the container, triggering a deprecation notice in Symfony 3.

I see two options to fix this problem:
1. Make the `stof_doctrine_extensions.listener.blameable` service public
2. [Preferred] Add a new public method called `setUserValue` to the public `stof_doctrine_extensions.event_listener.blame` service which in turn sets the user value on the `stof_doctrine_extensions.listener.blameable` service.
