### ISSUE TITLE
Missing code example in "Activate the extensions you want" section in GitHub preview, code is there in raw view

### ISSUE THREAD

**Issue by zoka123** [stof/StofDoctrineExtensionsBundle#293]
https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst#activate-the-extensions-you-want

**Comment by paq85** [comment]
:+1: 

This one is really confusing :|

**Comment by Lostmindy** [comment]
I concur, I were lost for a while until I decided to check the raw code.

**Comment by MauroCasula** [comment]
For example you can add how to activate blameable extension:

stof_doctrine_extensions:
    orm:
        default:
            blameable: true

**Comment by 228vit** [comment]
Still not fixed :(
Newcomers are loosing much time to make you bundle usable

**Comment by stof** [comment]
The documentation is now rendered on http://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html

Code snippets were missing because the doc was prepared for deployment on symfony.com (using rST features not supported by the github renderer) but not deployed yet. This is now fixed. The readme now links to the symfony.com website
