### ISSUE TITLE
support symfony 5

### ISSUE THREAD

**Issue by bruceleedrupal** [stof/StofDoctrineExtensionsBundle#406]
Can you tell me how long it will take to be compatable with symfony 5?

**Comment by david-wilson-mcn** [comment]
:+1:  I would appreciate this too, thanks

**Comment by maisoui** [comment]
👍 Me too, thanks.

**Comment by kl3sk** [comment]
At least you could use https://github.com/antishov/StofDoctrineExtensionsBundle

**Comment by yakobe** [comment]
@stof Is this repo maintained anymore? The last commit was a docs update in Jan 2019. Should it be marked as abandoned / not maintained to prevent dev's from getting into upgrade issues? 

Maybe they should be referred to https://github.com/KnpLabs/DoctrineBehaviors instead now?

**Comment by gregquat** [comment]
I don't think so. https://github.com/KnpLabs/DoctrineBehaviors has different approach, especially for Tree and Translatable.

**Comment by yakobe** [comment]
@gregquat that may be so, but if this is no longer maintained then it's still better for people to be directed to https://github.com/KnpLabs/DoctrineBehaviors. They can even contribute new features they need there.

**Comment by gregquat** [comment]
@yakobe The 2 philosophies aren't the same so I just think it's not a real solution to redirect to KNP.
The real solution now is to use the fork mentioned above by kl3sk and use https://github.com/antishov/StofDoctrineExtensionsBundle

This is a fork that supports symfony5. But of course, everybody does whatever he wants.

**Comment by TomasVotruba** [comment]
Just in case this might help anyone here.

I take care of DoctrineBehaviors since December 2019 and it has major release 2.0 with Symfony 5 support. These 2 bundles have 95 % overlapping features, so in case you use want to use Symfony 5, there is a way. 

You can read more about it:

- [Doctrine Behaviors 2.0 - Reloaded](https://www.tomasvotruba.com/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/)
- [Migrate Gedmo to KnpLabs](https://www.tomasvotruba.com/blog/2020/01/06/migrate-gedmo-to-knplabs/) - the migration is fully automated in PHP with @rectorphp, so don't worry about extra work

**Comment by stof** [comment]
1.4.0 is now released.
