### ISSUE TITLE
Generated Repository classes break after 1.5.0 update

### ISSUE THREAD

**Issue by BurningDog** [stof/StofDoctrineExtensionsBundle#419]
Running `composer update` on a Symfony 4.4 installation led to an error on each of my Repository classes (which were generated by `console make:entity`:

`Argument 1 passed to App\Repository\UserRepository::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given`

The fix is to change

* `use Doctrine\Common\Persistence\ManagerRegistry;` to
* `use Doctrine\Persistence\ManagerRegistry;`

This error exists because the 1.5.0 version of `stof/doctrine-extensions-bundle` now optionally requires v3.0.0 of `"gedmo/doctrine-extensions": "^2.3.4 || ^3.0.0"` which can bump `doctrine/common` from `2.*` to `3.x` - which changes the include path.

It would be great to have a warning about this somewhere when running `composer update` but I'm not sure _where_? Is this the `StofDoctrineExtensionsBundle` responsibility, or it is the responsibility of `doctrine/common`? I couldn't find anything on the Doctrine repo or website about this.

**Comment by derrabus** [comment]
`doctrine/persistence` did have a proper deprecation layer in place. There isn't much, this package can do about this kind of breaking change.

**Comment by stof** [comment]
In particular, this package is not responsible for the fact that your own project relies on transitive dependencies for the `doctrine/common` or `doctrine/persistence` package and so gets updated to the new major versions when your dependencies become compatible even if your own code has not been upgraded yet. The solution to this issue is that explicitly require packages that you directly use (so that your own constraint can be taken into account by composer).
